[opentelemetry]
extension=opentelemetry.so

[xdebug]
zend_extension=xdebug

; Enable Xdebug modes
xdebug.mode=develop,debug,profile

; Automatically start debugging when a request arrives
xdebug.start_with_request=trigger
xdebug.log=/tmp/xdebug.log
xdebug.log_level=10
xdebug.idekey=PHPSTORM

; Remote host (adjust if you’re not using Docker Desktop)
xdebug.client_host=host.docker.internal

; Output directory for profiler files
xdebug.output_dir=/home/appuser/debug

; Optional: name profiler files for easier identification
xdebug.profiler_output_name=cachegrind.out.%p
